[workspace]
members = [
	"node",
	"pallets/parachain-info",
	"pallets/ping",
	"rococo-runtime",
	"shell-runtime",
	"statemine-runtime",
	"statemint-common",
	"statemint-runtime",
	"westmint-runtime",
]

[profile.release]
panic = "unwind"
