
[workspace]
members = [
	"rococo-runtime",
	"pallets/parachain-info",
	"pallets/ping",
	"node",
	"shell-runtime",
	"statemine-runtime",
	"statemint-common",
	"statemint-runtime",
	"westmint-runtime",
	# "xcm-handler"
]

[profile.release]
panic = 'unwind'
