
[workspace]
members = [
	"rococo-runtime",
	"pallets/*",
	"node",
	"shell-runtime",
	"statemine-runtime",
	"statemint-common",
	"statemint-runtime",
	"westmint-runtime",
	"primitives",
	"primitives/starks",

]

[profile.release]
panic = 'unwind'
